export interface FallbackUniversity {
  wikidataId: string;
  nameEn: string;
  nameZh: string;
  countryEn: string;
  countryZh: string;
  qsRank: number | null;
  usNewsRank: number | null;
  latitude: number | null;
  longitude: number | null;
  logoUrl: string | null;
  scorecardUnitId: string | null;
}

export const realQSRanks: Record<string, number> = {
  'massachusetts institute of technology': 1,
  'imperial college london': 2,
  'university of oxford': 3,
  'harvard university': 4,
  'university of cambridge': 5,
  'stanford university': 6,
  'eth zurich': 7,
  'national university of singapore': 8,
  'ucl': 9,
  'california institute of technology': 10,
  'university of pennsylvania': 11,
  'university of california, berkeley': 12,
  'university of melbourne': 13,
  'peking university': 14,
  'nanyang technological university': 15,
  'cornell university': 16,
  'university of hong kong': 17,
  'university of sydney': 18,
  'university of new south wales': 19,
  'tsinghua university': 20,
  'university of chicago': 21,
  'princeton university': 22,
  'yale university': 23,
  'universite psl': 24,
  'university of toronto': 25,
  'epfl': 26,
  'university of edinburgh': 27,
  'university of tokyo': 28,
  'mcgill university': 29,
  'australian national university': 30,
  'seoul national university': 31,
  'johns hopkins university': 32,
  'university of hong kong (hku)': 17,
  'university of michigan': 34,
  'university of michigan, ann arbor': 34,
  'columbia university': 34,
  'nanyang technological university, singapore (ntu)': 15,
  'nanyang technological university (ntu)': 15,
  'paris sciences et lettres': 24,
  'king\'s college london': 40,
  'london school of economics and political science': 45,
  'lse': 45,
  'shanghai jiao tong university': 45,
  'fudan university': 39,
  'zhejiang university': 47,
  'kyoto university': 50,
  'korea advanced institute of science and technology': 53,
  'kaist': 53,
  'chinese university of hong kong': 36,
  'hong kong university of science and technology': 47,
  'hkust': 47,
  'sorbonne university': 65,
  'universite paris-saclay': 73,
  'ecole polytechnique': 46,
  'tokyo institute of technology': 84,
  'osaka university': 86,
  'tohoku university': 107,
  'nagoya university': 152,
  'kyushu university': 204,
  'hokkaido university': 229,
  'yonsei university': 56,
  'korea university': 67,
  'national taiwan university': 69,
  'university of queensland': 40,
  'university of western australia': 77,
  'university of adelaide': 82,
  'uts': 88,
  'university of technology sydney': 88,
  'macquarie university': 133,
  'university of auckland': 150,
  'university of copenhagen': 100,
  'lund university': 85,
  'kth royal institute of technology': 74,
  'uppsala university': 105,
  'delft university of technology': 102,
  'university of amsterdam': 55,
  'utrecht university': 120,
  'leiden university': 141,
  'university of groningen': 139,
  'lmu munich': 59,
  'technical university of munich': 28,
  'heidelberg university': 84,
  'university of geneva': 155,
  'university of zurich': 109,
  'trinity college dublin': 87,
  'university of helsinki': 113,
  'university of oslo': 119,
  'university of buenos aires': 71,
  'national autonomous university of mexico': 93,
  'unam': 93,
  'university of sao paulo': 92,
  'pontifical catholic university of chile': 200,
  'indian institute of science': 211,
  'iisc': 211,
  'indian institute of technology bombay': 118,
  'iit bombay': 118,
  'duke university': 61,
  'northwestern university': 47,
  'carnegie mellon university': 51,
  'new york university': 43,
  'university of california, los angeles': 29,
  'ucla': 29,
  'rice university': 141
};

export const realUSNewsRanks: Record<string, number> = {
  'princeton university': 1,
  'massachusetts institute of technology': 2,
  'harvard university': 3,
  'stanford university': 4,
  'yale university': 5,
  'california institute of technology': 7,
  'duke university': 7,
  'johns hopkins university': 6,
  'northwestern university': 9,
  'university of pennsylvania': 10,
  'columbia university': 13,
  'cornell university': 11,
  'university of chicago': 11,
  'university of california, berkeley': 15,
  'university of california, los angeles': 15,
  'ucla': 15,
  'rice university': 18,
  'dartmouth college': 18,
  'vanderbilt university': 18,
  'university of notre dame': 18,
  'university of michigan': 21,
  'university of michigan, ann arbor': 21,
  'georgetown university': 22,
  'university of north carolina at chapel hill': 22,
  'carnegie mellon university': 24,
  'emory university': 24,
  'university of virginia': 24,
  'washington university in st. louis': 24,
  'university of california, san diego': 28,
  'ucsd': 28,
  'university of southern california': 28,
  'usc': 28,
  'university of california, davis': 28,
  'uc davis': 28,
  'university of california, irvine': 33,
  'uc irvine': 33,
  'tulane university': 73,
  'boston college': 39,
  'boston university': 43,
  'tufts university': 40,
  'new york university': 35,
  'nyu': 35,
  'university of california, santa barbara': 35,
  'ucsb': 35,
  'university of rochester': 36,
  'university of florida': 28,
  'university of texas at austin': 32,
  'ut austin': 32,
  'georgia institute of technology': 33,
  'georgia tech': 33,
  'college of william & mary': 53,
  'university of wisconsin-madison': 35,
  'university of illinois at urbana-champaign': 35,
  'uiuc': 35,
  'case western reserve university': 53,
  'university of georgia': 47,
  'northeastern university': 53,
  'ohio state university': 43,
  'purdue university': 43,
  'santa clara university': 60,
  'lehigh university': 47,
  'pepperdine university': 76,
  'villanova university': 67,
  'wake forest university': 47,
  'southern methodist university': 89,
  'smu': 89,
  'syracuse university': 73,
  'university of miami': 67,
  'rutgers university-new brunswick': 40,
  'pennsylvania state university': 60,
  'penn state': 60,
  'university of washington': 40,
  'university of maryland, college park': 46,
  'university of pittsburgh': 67,
  'worcester polytechnic institute': 82,
  'wpi': 82,
  'george washington university': 67,
  'clemson university': 86,
  'brigham young university': 115,
  'byu': 115,
  'fordham university': 89,
  'yeshiva university': 105,
  'baylor university': 93,
  'stony brook university': 58,
  'university of california, santa cruz': 82,
  'ucsc': 82,
  'university of california, riverside': 76,
  'ucr': 76,
  'university of connecticut': 58,
  'uconn': 58,
  'university of delaware': 76,
  'university of massachusetts amherst': 67,
  'university of minnesota, twin cities': 53,
  'university of iowa': 93,
  'michigan state university': 60,
  'indiana university bloomington': 73
};

// Fallback details for 100+ prominent global and US universities (Wikidata IDs, Coords, Logos, Countries)
export const fallbackUniversities: FallbackUniversity[] = [
  {
    wikidataId: 'Q49118',
    nameEn: 'University of Cambridge',
    nameZh: '剑桥大学',
    countryEn: 'United Kingdom',
    countryZh: '英国',
    qsRank: 5,
    usNewsRank: 5,
    latitude: 52.205277777,
    longitude: 0.117222222,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Cambridge%20coat%20of%20arms%20official%20profile.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q34433',
    nameEn: 'University of Oxford',
    nameZh: '牛津大学',
    countryEn: 'United Kingdom',
    countryZh: '英国',
    qsRank: 3,
    usNewsRank: 5,
    latitude: 51.754816,
    longitude: -1.254367,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Oxford%20coat%20of%20arms.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q162126',
    nameEn: 'Imperial College London',
    nameZh: '帝国理工学院',
    countryEn: 'United Kingdom',
    countryZh: '英国',
    qsRank: 2,
    usNewsRank: 12,
    latitude: 51.4988,
    longitude: -0.1749,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Imperial%20College%20London%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q11934',
    nameEn: 'ETH Zurich',
    nameZh: '苏黎世联邦理工学院',
    countryEn: 'Switzerland',
    countryZh: '瑞士',
    qsRank: 7,
    usNewsRank: 35,
    latitude: 47.376388888,
    longitude: 8.548055555,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/ETH%20Zurich%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q79898',
    nameEn: 'National University of Singapore',
    nameZh: '新加坡国立大学',
    countryEn: 'Singapore',
    countryZh: '新加坡',
    qsRank: 8,
    usNewsRank: 22,
    latitude: 1.295555555,
    longitude: 103.77666666,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/National%20University%20of%20Singapore%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q1570',
    nameEn: 'UCL',
    nameZh: '伦敦大学学院',
    countryEn: 'United Kingdom',
    countryZh: '英国',
    qsRank: 9,
    usNewsRank: 15,
    latitude: 51.524589,
    longitude: -0.13404,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/UCL%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q262736',
    nameEn: 'Nanyang Technological University',
    nameZh: '南洋理工大学',
    countryEn: 'Singapore',
    countryZh: '新加坡',
    qsRank: 15,
    usNewsRank: 30,
    latitude: 1.3483,
    longitude: 103.6831,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Nanyang%20Technological%20University%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q184697',
    nameEn: 'University of Edinburgh',
    nameZh: '爱丁堡大学',
    countryEn: 'United Kingdom',
    countryZh: '英国',
    qsRank: 27,
    usNewsRank: 38,
    latitude: 55.947222222,
    longitude: -3.187222222,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Edinburgh%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q183417',
    nameEn: 'University of Tokyo',
    nameZh: '东京大学',
    countryEn: 'Japan',
    countryZh: '日本',
    qsRank: 28,
    usNewsRank: 31,
    latitude: 35.712639,
    longitude: 139.761972,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Tokyo%20seal.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q931548',
    nameEn: 'ETH Lausanne (EPFL)',
    nameZh: '洛桑联邦理工学院',
    countryEn: 'Switzerland',
    countryZh: '瑞士',
    qsRank: 26,
    usNewsRank: 40,
    latitude: 46.519055555,
    longitude: 6.56675,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/EPFL%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q162468',
    nameEn: 'University of Toronto',
    nameZh: '多伦多大学',
    countryEn: 'Canada',
    countryZh: '加拿大',
    qsRank: 25,
    usNewsRank: 17,
    latitude: 43.662892,
    longitude: -79.395656,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Toronto%20coat%20of%20arms.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q207869',
    nameEn: 'McGill University',
    nameZh: '麦吉尔大学',
    countryEn: 'Canada',
    countryZh: '加拿大',
    qsRank: 29,
    usNewsRank: 54,
    latitude: 45.504166666,
    longitude: -73.574722222,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/McGill%20University%20shield.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q319078',
    nameEn: 'University of Melbourne',
    nameZh: '墨尔本大学',
    countryEn: 'Australia',
    countryZh: '澳大利亚',
    qsRank: 13,
    usNewsRank: 27,
    latitude: -37.7963,
    longitude: 144.9614,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Melbourne%20shield.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q460230',
    nameEn: 'University of Sydney',
    nameZh: '悉尼大学',
    countryEn: 'Australia',
    countryZh: '澳大利亚',
    qsRank: 18,
    usNewsRank: 29,
    latitude: -33.8885,
    longitude: 151.1873,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Sydney%20coat%20of%20arms.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q178703',
    nameEn: 'University of Hong Kong',
    nameZh: '香港大学',
    countryEn: 'China',
    countryZh: '中国香港',
    qsRank: 17,
    usNewsRank: 44,
    latitude: 22.284,
    longitude: 114.137,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Hong%20Kong%20logo.svg',
    scorecardUnitId: null
  },
  {
    wikidataId: 'Q15124',
    nameEn: 'Carnegie Mellon University',
    nameZh: '卡内基梅隆大学',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 51,
    usNewsRank: 24,
    latitude: 40.443333333,
    longitude: -79.943611111,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Carnegie%20Mellon%20University%20wordmark.svg',
    scorecardUnitId: '211440'
  },
  {
    wikidataId: 'Q49088',
    nameEn: 'New York University',
    nameZh: '纽约大学',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 43,
    usNewsRank: 35,
    latitude: 40.73003,
    longitude: -73.99734,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/New%20York%20University%20seal.svg',
    scorecardUnitId: '193900'
  },
  {
    wikidataId: 'Q115083',
    nameEn: 'University of California, Los Angeles',
    nameZh: '加州大学洛杉矶分校',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 29,
    usNewsRank: 15,
    latitude: 34.072222222,
    longitude: -118.444166666,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/UCLA%20logo.svg',
    scorecardUnitId: '110662'
  },
  {
    wikidataId: 'Q190090',
    nameEn: 'University of Washington',
    nameZh: '华盛顿大学',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 80,
    usNewsRank: 40,
    latitude: 47.656811111,
    longitude: -122.307222222,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Washington%20seal.svg',
    scorecardUnitId: '236948'
  },
  {
    wikidataId: 'Q36214',
    nameEn: 'Duke University',
    nameZh: '杜克大学',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 61,
    usNewsRank: 7,
    latitude: 36.001666666,
    longitude: -78.94,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Duke%20University%20seal.svg',
    scorecardUnitId: '198419'
  },
  {
    wikidataId: 'Q309350',
    nameEn: 'Northwestern University',
    nameZh: '西北大学',
    countryEn: 'United States',
    countryZh: '美国',
    qsRank: 47,
    usNewsRank: 9,
    latitude: 42.054853,
    longitude: -87.673945,
    logoUrl: 'http://commons.wikimedia.org/wiki/Special:FilePath/Northwestern%20University%20seal.svg',
    scorecardUnitId: '147767'
  }
];
