/**
 * Zero-dependency Bidirectional Chinese Localization Engine.
 * Provides high-performance conversions between Simplified Chinese (简体中文) 
 * and Traditional Chinese (繁体中文) for all university and major names.
 */

// Common character mappings for academic terms and university names
const s2tMap: Record<string, string> = {
  '学': '學',
  '国': '國',
  '华': '華',
  '剑': '劍',
  '桥': '橋',
  '鲁': '魯',
  '伦': '倫',
  '亚': '亞',
  '宾': '賓',
  '莱': '萊',
  '麦': '麥',
  '尔': '爾',
  '兰': '蘭',
  '奥': '奧',
  '达': '達',
  '温': '溫',
  '会': '會',
  '计': '計',
  '经': '經',
  '济': '濟',
  '理': '理',
  '工': '工',
  '科': '科',
  '术': '術',
  '艺': '藝',
  '创': '創',
  '新': '新',
  '管': '管',
  '商': '商',
  '业': '業',
  '电': '電',
  '机': '機',
  '器': '器',
  '软': '軟',
  '数': '數',
  '统': '統',
  '医': '醫',
  '药': '藥',
  '护': '護',
  '环': '環',
  '境': '境',
  '资': '資',
  '源': '源',
  '发': '發',
  '展': '展',
  '语': '語',
  '言': '言',
  '传': '傳',
  '播': '播',
  '历': '歷',
  '律': '律',
  '行': '行',
  '东': '東',
  '西': '西',
  '南': '南',
  '北': '北',
  '京': '京',
  '湾': '灣',
  '港': '港',
  '门': '門',
  '欧': '歐',
  '美': '美',
  '际': '際',
  '关': '關',
  '联': '聯',
  '协': '協',
  '研': '研',
  '究': '究',
  '硕': '碩',
  '博': '博',
  '优': '優',
  '特': '特',
  '专': '專',
  '课': '課',
  '程': '程',
  '教': '教',
  '育': '育',
  '体': '體',
  '军': '軍',
  '气': '氣',
  '农': '農',
  '渔': '漁',
  '园': '園',
  '植': '植',
  '细': '細',
  '态': '態',
  '区': '區',
  '老': '老',
  '儿': '兒',
  '残': '殘',
  '红': '紅',
  '团': '團',
  '义': '義',
  '导': '導',
  '实': '實',
  '验': '驗',
  '系': '系',
  '筑': '築',
  '设': '設',
  '视': '視',
  '觉': '覺',
  '媒': '媒',
  '动': '動',
  '画': '畫',
  '戏': '戲',
  '剧': '劇',
  '乐': '樂',
  '写': '寫',
  '闻': '聞',
  '广': '廣',
  '营': '營',
  '养': '養',
  '临': '臨',
  '床': '床',
  '应': '應',
  '精': '精',
  '算': '算',
  '融': '融',
  '险': '險',
  '审': '審',
  '安': '安',
  '全': '全',
  '网': '網',
  '络': '絡',
  '冶': '冶',
  '矿': '礦',
  '油': '油',
  '牧': '牧',
  '遗': '遺',
  '社区': '社區',
  '历史': '歷史',
  '毕': '畢',
  '波': '波',
  '士': '士',
  '顿': '頓',
  '芝': '芝',
  '加': '加',
  '哥': '哥',
  '雅': '雅',
  '图': '圖',
  '洛': '洛',
  '杉': '杉',
  '矶': '磯',
  '旧': '舊',
  '山': '山',
  '苏': '蘇',
  '首': '首',
  '隆': '隆',
  '曼': '曼',
  '谷': '谷',
  '魁': '魁',
  '蒙': '蒙',
  '爱': '愛',
  '塞': '塞',
  '阿': '阿',
  '辛': '辛',
  '内': '內',
  '瓦': '瓦',
  '罗': '羅',
  '马': '馬',
  '萨': '薩',
  '里斯': '里斯',
  '布': '布',
  '约': '約',
  '翰': '翰',
  '斯': '斯',
  '竹': '竹',
  '台': '台',
  '高': '高',
  '雄': '雄',
  '桃': '桃',
  '基': '基',
  '宜': '宜',
  '花': '花',
  '莲': '蓮',
  '澎': '澎',
  '湖': '湖',
  '金': '金',
  '祖': '祖',
  '纳': '納',
  '圣': '聖',
  '伯': '伯',
  '克': '克',
  '柏': '柏',
  '利': '利',
  '生': '生',
};

// Build Traditional -> Simplified mapping dynamically
const t2sMap: Record<string, string> = {};
for (const [s, t] of Object.entries(s2tMap)) {
  t2sMap[t] = s;
}

// Additional specific Traditional -> Simplified overrides for mixed data patterns
const traditionalOverrides: Record<string, string> = {
  '學院': '学院',
  '大學': '大学',
  '國立': '国立',
  '華': '华',
  '劍': '剑',
  '橋': '桥',
  '蘭': '兰',
  '麥': '麦',
  '爾': '尔',
  '東': '东',
  '西': '西',
  '南': '南',
  '北': '北',
  '京': '京',
  '灣': '湾',
  '港': '港',
  '門': '门',
  '歐': '欧',
  '美': '美',
  '際': '际',
  '關': '关',
  '聯': '联',
  '協': '协',
  '研': '研',
  '究': '究',
  '碩': '硕',
  '博': '博',
  '優': '优',
  '特': '特',
  '專': '专',
  '課': '课',
  '程': '程',
  '教': '教',
  '育': '育',
  '體': '体',
  '軍': '军',
  '氣': '气',
  '農': '农',
  '漁': '渔',
  '園': '园',
  '植': '植',
  '細': '细',
  '態': '态',
  '區': '区',
  '老': '老',
  '兒': '儿',
  '殘': '残',
  '紅': '红',
  '團': '团',
  '義': '义',
  '導': '导',
  '實': '实',
  '驗': '验',
  '築': '筑',
  '設': '设',
  '視': '视',
  '覺': '觉',
  '媒': '媒',
  '動': '动',
  '畫': '画',
  '戲': '戏',
  '劇': '剧',
  '樂': '乐',
  '寫': '写',
  '新': '新',
  '聞': '闻',
  '廣': '广',
  '營': '营',
  '養': '养',
  '臨': '临',
  '床': '床',
  '應': '应',
  '精': '精',
  '算': '算',
  '融': '融',
  '險': '险',
  '審': '审',
  '安': '安',
  '全': '全',
  '網': '网',
  '絡': '络',
  '製': '制',
  '造': '造',
  '計': '计',
  '經': '经',
  '濟': '济',
  '統': '统',
  '會': '会',
  '盧': '卢',
  '魯': '鲁',
  '倫': '伦',
  '亞': '亚',
  '賓': '宾',
  '萊': '莱',
  '奧': '奥',
  '達': '达',
  '溫': '温',
  '理': '理',
  '工': '工',
  '科': '科',
  '術': '术',
  '藝': '艺',
  '創': '创',
  '管': '管',
  '商': '商',
  '業': '业',
  '電': '电',
  '機': '机',
  '器': '器',
  '軟': '软',
  '數': '数',
  '醫': '医',
  '藥': '药',
  '護': '护',
  '環': '环',
  '境': '境',
  '資': '资',
  '源': '源',
  '發': '发',
  '展': '展',
  '語': '语',
  '言': '言',
  '傳': '传',
  '播': '播',
  '歷': '历',
  '律': '律',
  '行': '行',
  '里': '里',
  '斯': '斯',
  '柏': '柏',
  '克': '克',
  '利': '利',
  '伯': '伯',
  '波': '波',
  '士': '士',
  '頓': '顿',
  '芝': '芝',
  '加': '加',
  '哥': '哥',
  '雅': '雅',
  '圖': '图',
  '洛': '洛',
  '杉': '杉',
  '磯': '矶',
  '舊': 'old',
  '金': '金',
  '山': '山',
  '蘇': '苏',
  '首': '首',
  '隆': '隆',
  '曼': '曼',
  '谷': '谷',
  '魁': '魁',
  '蒙': '蒙',
  '愛': '爱',
  '塞': '塞',
  '阿': 'ag',
  '辛': '辛',
  '內': '内',
  '瓦': '瓦',
  '羅': '罗',
  '馬': '马',
  '薩': '萨',
  '布': '布',
  '約': '约',
  '翰': '翰',
  '台': '台',
  '中': '中',
  '高': '高',
  '雄': '雄',
  '桃': '桃',
  '基': '基',
  '宜': '宜',
  '花': '花',
  '蓮': '莲',
  '澎': '澎',
  '湖': '湖',
  '祖': '祖',
  '聖': '圣',
};

// Merge specific Traditional -> Simplified overrides into our main map
for (const [t, s] of Object.entries(traditionalOverrides)) {
  t2sMap[t] = s;
}

// Specific English -> Chinese localization dictionary overrides for 100% pixel-perfect translation consistency
const universityOverrideZh: Record<string, string> = {
  'harvard': '哈佛大学',
  'mit': '麻省理工学院',
  'stanford': '斯坦福大学',
  'berkeley': '加州大学伯克利分校',
  'princeton': '普林斯顿大学',
  'yale': '耶鲁大学',
  'upenn': '宾夕法尼亚大学',
  'caltech': '加州理工学院',
  'columbia': '哥伦比亚大学',
  'chicago': '芝加哥大学',
  'umich': '密歇根大学安娜堡分校',
  'rice': '莱斯大学',
  'tsinghua': '清华大学',
  'peking': '北京大学',
  'oxford': '牛津大学',
  'nus': '新加坡国立大学',
};

const universityOverrideZht: Record<string, string> = {
  'harvard': '哈佛大學',
  'mit': '麻省理工學院',
  'stanford': '斯坦福大學',
  'berkeley': '加州大學柏克萊分校',
  'princeton': '普林斯頓大學',
  'yale': '耶魯大學',
  'upenn': '宾夕法尼亞大學',
  'caltech': '加州理工學院',
  'columbia': '哥倫比亞大學',
  'chicago': '芝加哥大學',
  'umich': '密西根大學安娜堡分校',
  'rice': '萊斯大學',
  'tsinghua': '清華大學',
  'peking': '北京大學',
  'oxford': '牛津大學',
  'nus': '新加坡國立大學',
};

/**
 * Converts any Chinese string from Simplified to Traditional Chinese.
 */
export function toTraditional(str: string): string {
  if (!str) return '';
  let result = '';
  for (let i = 0; i < str.length; i++) {
    const char = str[i];
    result += s2tMap[char] || char;
  }
  return result;
}

/**
 * Converts any Chinese string from Traditional to Simplified Chinese.
 */
export function toSimplified(str: string): string {
  if (!str) return '';
  let result = '';
  for (let i = 0; i < str.length; i++) {
    const char = str[i];
    result += t2sMap[char] || char;
  }
  return result;
}

/**
 * Resolves a pixel-perfect Simplified Chinese name for a university.
 */
export function getUniversityNameZh(id: string, fallbackName: string): string {
  const override = universityOverrideZh[id.toLowerCase()];
  if (override) return override;
  return toSimplified(fallbackName);
}

/**
 * Resolves a pixel-perfect Traditional Chinese name for a university.
 */
export function getUniversityNameZht(id: string, fallbackName: string): string {
  const override = universityOverrideZht[id.toLowerCase()];
  if (override) return override;
  return toTraditional(toSimplified(fallbackName)); // Convert to simplified first to normalize, then to traditional
}
